//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.31 at 10:18:16 AM CEST 
//


package com.scorsaro.coffee;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.scorsaro.coffee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.scorsaro.coffee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCoffeeRequest }
     * 
     */
    public GetCoffeeRequest createGetCoffeeRequest() {
        return new GetCoffeeRequest();
    }

    /**
     * Create an instance of {@link GetCoffeeResponse }
     * 
     */
    public GetCoffeeResponse createGetCoffeeResponse() {
        return new GetCoffeeResponse();
    }

    /**
     * Create an instance of {@link Coffee }
     * 
     */
    public Coffee createCoffee() {
        return new Coffee();
    }

}
