//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.31 at 10:18:16 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://scorsaro.com/coffee", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.scorsaro.coffee;
